structure(list(url = "https://api.scb.se/OV0104/?config", status_code = 200L, 
    headers = structure(list(date = "Thu, 25 Jun 2026 09:14:17 GMT", 
        `content-length` = "0", `access-control-allow-origin` = "*", 
        `access-control-allow-methods` = "GET,POST", `access-control-max-age` = "86400", 
        allow = "GET,HEAD,POST,OPTIONS", vary = "Origin", `strict-transport-security` = "max-age=31536000; includeSubDomains"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "text/html; charset=UTF-8", 
            location = "https://api.scb.se/OV0104/?config", date = "Thu, 25 Jun 2026 09:14:17 GMT", 
            `content-length` = "155", `access-control-allow-origin` = "*", 
            `access-control-allow-methods` = "GET,POST", `access-control-max-age` = "86400", 
            allow = "GET,HEAD,POST,OPTIONS", vary = "Origin, Accept-Encoding", 
            `strict-transport-security` = "max-age=31536000; includeSubDomains"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 25 Jun 2026 09:14:17 GMT", 
            `content-length` = "0", `access-control-allow-origin` = "*", 
            `access-control-allow-methods` = "GET,POST", `access-control-max-age` = "86400", 
            allow = "GET,HEAD,POST,OPTIONS", vary = "Origin", 
            `strict-transport-security` = "max-age=31536000; includeSubDomains"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_.api.scb.se", 
        flag = TRUE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "TS0187a64b", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = raw(0), date = structure(1782378857, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0.044838, 
    namelookup = 0, connect = 0, pretransfer = 0.000369, starttransfer = 0.088245, 
    total = 0.088394)), class = "response")
