structure(list(url = "https://api.scb.se/OV0104/v1/doris?config", 
    status_code = 404L, headers = structure(list(`content-type` = "text/html", 
        date = "Thu, 25 Jun 2026 09:14:17 GMT", `content-length` = "1245", 
        `access-control-allow-origin` = "*", `access-control-allow-methods` = "GET,POST", 
        `access-control-max-age` = "86400", allow = "GET,HEAD,POST,OPTIONS", 
        vary = "Origin", `strict-transport-security` = "max-age=31536000; includeSubDomains"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "text/html", 
            date = "Thu, 25 Jun 2026 09:14:17 GMT", `content-length` = "1245", 
            `access-control-allow-origin` = "*", `access-control-allow-methods` = "GET,POST", 
            `access-control-max-age` = "86400", allow = "GET,HEAD,POST,OPTIONS", 
            vary = "Origin", `strict-transport-security` = "max-age=31536000; includeSubDomains"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_.api.scb.se", 
        flag = TRUE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "TS0187a64b", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>404 - File or directory not found.</title>\r\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div class=\"content-container\"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n"), 
    date = structure(1782378857, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0, 
    connect = 0, pretransfer = 2e-04, starttransfer = 0.034743, 
    total = 0.034808)), class = "response")
